clc;clear;close all;
filename1='DBS Group Holdings Ltd.csv';
filename2='Global Investments Ltd.csv';
filename3='Great Eastern Hldgs Ltd.csv';
filename4='JAMB Syllabus-A levels combined.csv';
filename5='Oversea-Chinese Banking Corp.csv';
filename6='Singapore Exchange Ltd.csv';
filename7='United Overseas Bank Ltd.csv';
[Open, High, Low, Close,volume,Adj]=fileload(filename1);
%Display('ARIMA',Adj);
%Display('ANN',Adj);
%Display('SVR',Adj);
%Display('RF',Adj);
%Display('PSO',Adj);
%Display('PSOARIMA',Adj);
%Display('PSOSVR',Adj);
%Display('PSORF',Adj);
%Display('EMD',Adj);
%Display('PSOEMD_ARIMA',Adj);
Display('PSOEMD_SVR',Adj);
%Display('PSOEMD_RF',Adj);
%Display('EMD_ANN',Adj);